---

- name: Ensure git is present
  package:
    name: git
    state: present

- name: git clone faup
  git:
    repo: https://github.com/stricaud/faup.git
    dest: "{{ toolsetdir }}/faup"
    version: "{{ faup_version | default('685acb0d4c936f97782497a684764671728eda78') }}"

- name: faup dependencies
  package: name={{ item }} state=present
  with_items: "{{ faup_deps }}"
  register: pkg_result
  until: pkg_result is success

- name: Redhat8 | force latest libarchive - cmake workaround  # noqa package-latest
  package:
    name: libarchive
    state: latest
  when: (ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 8)

- name: faup | compile
  command: "{{ item }}"
  args:
    chdir: "{{ toolsetdir }}/faup/build"
    creates: "{{ toolsetdir }}/faup/build/src/tools/faup"
  with_items:
    - cmake ..
    - make
- name: Ubuntu | ensure appropriate path for shared libraries
  lineinfile:
    dest: /etc/ld.so.conf.d/x86_64-linux-gnu.conf
    line: '/usr/local/lib/x86_64-linux-gnu'
    mode: '0644'
    create: yes
  when: ansible_distribution == 'Ubuntu'
  notify:
    - run ldconfig
- name: RedHat | ensure appropriate path for shared libraries
  lineinfile:
    dest: /etc/ld.so.conf.d/x86_64-linux-gnu.conf
    line: '/usr/local/lib64'
    mode: '0644'
    create: yes
  when: ansible_os_family == "RedHat"
  notify:
    - run ldconfig

- name: faup | install
  command: "{{ item }}"
  args:
    chdir: "{{ toolsetdir }}/faup/build"
    creates: "/usr/local/bin/faup"
  with_items:
    - make install
  notify:
    - run ldconfig

- block:
    - name: install faup python bindings
      command: "{{ faup_python_bin }} setup.py install"
      args:
        chdir: "{{ toolsetdir }}/faup/src/lib/bindings/python"
        creates: "{{ faup_python_bindings }}"
  when: faup_virtualenv_path is not defined or not faup_virtualenv_path

- block:
    - name: virtualenv dependencies
      package:
        name: "{{ faup_python_pkgs }}"
        state: present
      register: pkg_install
      until: pkg_install is success
    # if user exists with running process, usermod can't edit it and fails
    - name: check if virtualenv user {{ faup_virtualenv_user }} exists
      command: "grep {{ faup_virtualenv_user }} /etc/passwd"
      changed_when: false
      ignore_errors: true
      register: haveuser
    - name: ensure virtualenv user {{ faup_virtualenv_user }} exists
      user:
        name: "{{ faup_virtualenv_user }}"
        home: "{{ faup_virtualenv_home }}"
        state: present
      when: haveuser is failed and faup_virtualenv_user != 'root' and faup_virtualenv_user != 'nobody' and faup_virtualenv_user != 'www-data'
    # - name: debian | install faup python bindings - virtualenv
    #   pip:
    #     name: "file://{{ toolsetdir }}/faup/src/lib/bindings/python"
    #     virtualenv: "{{ faup_virtualenv_path }}"
    ### FIXME! end with owner root
    #   become: yes
    #   become_user: "{{ faup_virtualenv_user }}"
    #   when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
    ## centos7: previous command fails silently
    - name: ensure virtualenv dirname path exists
      file:
        dest: "{{ faup_virtualenv_path | dirname }}"
        state: directory
        mode: '0755'
        owner: "{{ faup_virtualenv_user }}"
      when: faup_virtualenv_path | dirname | dirname != '/home'
    - name: ensure directories ownership if needed, like pip cache
      file:
        dest: "{{ item.d }}"
        state: "{{ item.s }}"
        mode: "{{ item.m }}"
        owner: "{{ item.o }}"
      with_items: "{{ faup_ownership | default([]) }}"
    - name: install faup python bindings - virtualenv
      command: "{{ item.c }}"
      args:
        creates: "{{ item.t }}"
      with_items:
        - { c: "virtualenv -p {{ faup_python_bin }} {{ faup_virtualenv_path }}", t: "{{ faup_virtualenv_path }}" }
        - { c: "{{ faup_virtualenv_path }}/bin/pip install file://{{ toolsetdir }}/faup/src/lib/bindings/python/",
            t: "{{ faup_python_bindings | regex_replace('/usr', faup_virtualenv_path) }}"
        }
      become: yes
      become_user: "{{ faup_virtualenv_user }}"
      # when: ansible_os_family == "RedHat"
      ## FIXME! not idempotent
      # - name: ensure right permissions
      #   file: "dest={{ faup_virtualenv_path }} state=directory owner={{ faup_virtualenv_user }} recurse=yes"
      #   command: "{{ item }}"
      #   args:
      #     chdir: "{{ toolsetdir }}/faup/src/lib/bindings/python"
      #     creates: "{{ faup_virtualenv_path }}/lib/python2.7/site-packages/pyfaup-1.0-py2.7.egg"
      #   with_items:
      #     - "{{ faup_virtualenv_path }}/bin/python setup.py build"
      #     - "{{ faup_virtualenv_path }}/bin/python setup.py install"
  when: faup_virtualenv_path is defined and faup_virtualenv_path
